import { AxiosError } from 'axios';

export const error: AxiosError = {
  name: 'Test Error',
  config: {},
  message: 'An error occurred during testing'
};
